import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Hi, This is React Library Test Page</h1>
        <Link href="/react-hook-form">React-Hook-Form</Link> <br />
        <Link href="/react-query">React-Query</Link>
      </div>
    </>
  );
}
